steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://master_keys/imitation-applications/master.key', './config/']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$_PROJECT_ID/imitation-applications", "-f", "DockerfilePrd", "."]
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$_PROJECT_ID/imitation-applications"]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'imitation-applications', '--image', 'gcr.io/$_PROJECT_ID/imitation-applications', '--region', 'asia-northeast1','--platform', 'managed', '--quiet']
images:
  - gcr.io/$_PROJECT_ID/imitation-applications
